use_frameworks!

platform :ios, '9.0'

target 'MTIQKeyboardManager_Example' do
  pod 'MTIQKeyboardManager', :path => '../'

  target 'MTIQKeyboardManager_Tests' do
    inherit! :search_paths

    
  end
end
